### ISSUE TITLE
Newest version is not released to crates.io

### ISSUE THREAD

**Issue by TilBlechschmidt** [21re/rust-geo-booleanop#30]
The newest commit including a bump of the `geo` dependency does not seem to be included in the latest release published to crates.io — this causes a major headache when using the currently latest version of `geo` and throws one into the deep dependency hell that cargo digs for oneself ...

In order to not end up in hell, I'd appreciate a new release to cargo so I don't have to pull the latest release from GitHub all the time 😜

For everyone that stumbles upon this bug report in the meantime, you may use this to alleviate your pain temporarily:
```toml
geo-booleanop = { git = "https://github.com/21re/rust-geo-booleanop" }
```

**Comment by TilBlechschmidt** [comment]
Oh and on the topic of dependency management: `geo` has received version `0.18` so it might be favourable to bump it before publishing a new release 🙂

**Comment by Shatur** [comment]
@aloise why it was closed?
